-- Se debe ejecutar desde usuario system
-- CREAR TABLESPACES Y DATAFILES
CREATE TABLESPACE "TSTECH1" DATAFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSTECH1.DBF' SIZE 1000M;
CREATE TEMPORARY TABLESPACE "TSTECH1_TEMP" TEMPFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSTECH1_TEMP.DBF' SIZE 1000M;

--CREAR USUARIO
CREATE USER TECH1 IDENTIFIED BY 1234 DEFAULT TABLESPACE TSTECH1 TEMPORARY TABLESPACE TSTECH1_TEMP;

--DAR PERMISOS A USUARIO ADMIN SOBRE TABLESPACES
GRANT UNLIMITED TABLESPACE TO TECH1;

--DAR ROL ADMIN A USUARIO
GRANT CONNECT, RESOURCE, DBA TO TECH1;