CREATE OR REPLACE PACKAGE BODY TECH2.PKG_TRANSACCION2 IS
	
	PROCEDURE prHACER_TRANSACCION2 (
		ircTRANSACCION IN OUT nocopy TECH1.SYN_TY_TRANSACCION,
		idERROR OUT NUMBER,
		MSG OUT VARCHAR2
	) IS
	BEGIN
		-- Llamado a procedimiento en capa de exposición de esquema TECH1
		TECH1.PKG_CEX_TRANSACCION.prHACER_TRANSACCION(ircTRANSACCION, idERROR, MSG);
	END prHACER_TRANSACCION2;

END PKG_TRANSACCION2;