CREATE OR REPLACE PACKAGE TECH2.PKG_TRANSACCION2 IS
	
	PROCEDURE prHACER_TRANSACCION2 (
		ircTRANSACCION IN OUT nocopy TECH1.SYN_TY_TRANSACCION,
		idERROR OUT NUMBER,
		MSG OUT VARCHAR2
	);

END PKG_TRANSACCION2;