-- Ejecutar desde usuario system
-- CREAR TABLESPACES Y DATAFILES
CREATE TABLESPACE "TSTECH2" DATAFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSTECH2.DBF' SIZE 1000M;
CREATE TEMPORARY TABLESPACE "TSTECH2_TEMP" TEMPFILE 'C:\app\Chiefpc\product\21c\oradata\XE\TSTECH2_TEMP.DBF' SIZE 1000M;

--CREAR USUARIO
CREATE USER TECH2 IDENTIFIED BY 1234 DEFAULT TABLESPACE TSTECH2 TEMPORARY TABLESPACE TSTECH2_TEMP;

--DAR ROL ADMIN A USUARIO
GRANT CONNECT, RESOURCE TO TECH2;

-- DAR ACCESO SOBRE EL PAQUETE DE EXPOSICIÓN DEL ESQUEMA PRINCIPAL
GRANT EXECUTE ON TECH1.PKG_CEX_TRANSACCION TO TECH2;

-- DAR ACCESO SOBRE LOS SINÓNIMOS DEL ESQUEMA PRINCIPAL
GRANT EXECUTE ON TECH1.SYN_TY_TRANSACCION TO TECH2;